version: '2'

linters:
  default: all
  disable:
    # deprecated
    - wsl
    # rule dependencies in other way
    - depguard
    # just use more examples
    - revive
  settings:
    cyclop:
      max-complexity: 12
    gocritic:
      enable-all: true
      disabled-checks:
        - unnamedResult
        - paramTypeCombine
    ireturn:
      allow:
        - error
        - generic
    wrapcheck:
      ignore-package-globs:
        - github.com/therenotomorrow/ex
  exclusions:
    rules:
      # simple rules for examples and tests
      - path: _test\.go
        linters:
          - exhaustruct
          - funlen

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    golines:
      max-len: 120
      tab-len: 4
      shorten-comments: true
      chain-split-dots: true

issues:
  fix: true
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  show-stats: true

run:
  go: '1.24'
  allow-parallel-runners: true
  timeout: 5m
